# Generated by Django 5.2.9 on 2025-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='مبلغ التوصيل'),
        ),
    ]
