# Generated by Django 5.1 on 2025-12-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_profile_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان السكشن')),
                ('section_type', models.CharField(choices=[('slider', 'شريط متحرك (Slider)'), ('grid', 'شبكة منتجات (Grid)')], default='grid', max_length=20, verbose_name='طريقة العرض')),
                ('product_count', models.IntegerField(default=8, verbose_name='عدد المنتجات المعروضة')),
                ('ordering', models.IntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='القسم (اختياري)')),
            ],
            options={
                'verbose_name': 'قسم الصفحة الرئيسية',
                'verbose_name_plural': 'أقسام الصفحة الرئيسية',
                'ordering': ['ordering'],
            },
        ),
    ]
